export { buildAttemptActions } from "./lib/attemptActions";
export { buildFeedItems } from "./lib/buildFeed";
export type { FeedBuildSource } from "./lib/buildFeed";
export { buildQueueItems, buildStudentTiles } from "./lib/buildMonitorModel";
export { compareWithEtalon } from "./lib/compareWithEtalon";
export { formatElapsed } from "./lib/formatElapsed";
export { findIssuedAt, findOpenAttempt, reduceLiveStates, sumErrors } from "./lib/liveState";
export type { AttemptLive, StudentLive } from "./lib/liveState";
export type { MonitorSource } from "./lib/monitorSource";
export { buildStudentState, OFFLINE_SILENCE_MS } from "./lib/studentState";
export type { StudentStateView } from "./lib/studentState";
export { defaultMonitorApi, defaultMonitorDeps, MonitorDepsContext, useMonitorDeps } from "./model/deps";
export type { MonitorApi, MonitorDeps } from "./model/deps";
export { useCardCaptions } from "./model/useCardCaptions";
export { useLiveSession } from "./model/useLiveSession";
export type { LiveSession, LiveSessionState } from "./model/useLiveSession";
export { useMonitorFeed } from "./model/useMonitorFeed";
export { useMonitorReference } from "./model/useMonitorReference";
export type { MonitorReference } from "./model/useMonitorReference";
export { useStudents } from "./model/useStudents";
export { useNow } from "./model/useNow";
export type { ActionCheckRow, CardCaptionMap, MonitorStudent } from "./model/types";
export type { FeedItem, QueueItem, SessionHeaderModel } from "./model/types";
export type { SnapshotAction, StudentTileModel } from "./model/types";
/* Тестовые зависимости мониторинга — публичны, чтобы экраны преподавателя тестировались теми же стабами. */
export { createTestApi, createTestClock, withDeps } from "./model/testDeps.testing";
export type { TestApiOverrides } from "./model/testDeps.testing";
export { MonitorBoard } from "./ui/MonitorBoard";
export { SessionHeader } from "./ui/SessionHeader";
export { StudentActions } from "./ui/StudentActions";
