"""initial

Revision ID: 0001_initial
Revises: None
Create Date: 2026-09-28 23:28:37.999254
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arm_card_fixtures',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('card_status', sa.String(length=24), nullable=False),
    sa.Column('classifier_code', sa.String(length=16), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arm_card_fixtures_number'), 'arm_card_fixtures', ['number'], unique=False)
    op.create_table('assignment_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.String(length=16), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=False),
    sa.Column('card_id', sa.String(length=16), nullable=False),
    sa.Column('attempt_id', sa.String(length=16), nullable=False),
    sa.Column('replays', sa.Integer(), nullable=False),
    sa.Column('hints_shown', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_attempts_assignment_id'), 'assignment_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_attempts_attempt_id'), 'assignment_attempts', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_assignment_attempts_student_id'), 'assignment_attempts', ['student_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('teacher_id', sa.String(length=16), nullable=False),
    sa.Column('student_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('training_mode', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('card_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('random_rule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('due_at', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_state'), 'assignments', ['state'], unique=False)
    op.create_index(op.f('ix_assignments_teacher_id'), 'assignments', ['teacher_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=24), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.String(length=32), nullable=False),
    sa.Column('primary_reaction_ms', sa.Integer(), nullable=False),
    sa.Column('statuses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('services_called', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('full_processing_ms', sa.Integer(), nullable=False),
    sa.Column('entered_text', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('calls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('card_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answered_at', sa.String(length=32), nullable=True),
    sa.Column('aon', sa.String(length=32), nullable=True),
    sa.Column('incident_number', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_card_id'), 'attempts', ['card_id'], unique=False)
    op.create_index(op.f('ix_attempts_session_id'), 'attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_attempts_student_id'), 'attempts', ['student_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.String(length=2000), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('operator_arm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('calibration_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_samples_attempt_id'), 'calibration_samples', ['attempt_id'], unique=False)
    op.create_table('card_runtime',
    sa.Column('card_id', sa.String(length=24), nullable=False),
    sa.Column('status_events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('work_lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reminders', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('card_work_messages',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('attempt_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.Column('expected_status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_work_messages_at'), 'card_work_messages', ['at'], unique=False)
    op.create_index(op.f('ix_card_work_messages_attempt_id'), 'card_work_messages', ['attempt_id'], unique=False)
    op.create_table('classifier_entries',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('group', sa.String(length=160), nullable=False),
    sa.Column('sign1', sa.String(length=160), nullable=False),
    sa.Column('sign2', sa.String(length=160), nullable=False),
    sa.Column('sign3', sa.String(length=160), nullable=False),
    sa.Column('extra_signs', sa.String(length=400), nullable=False),
    sa.Column('final_type', sa.String(length=400), nullable=False),
    sa.Column('ekp35_type', sa.String(length=400), nullable=False),
    sa.Column('main_service', sa.String(length=64), nullable=False),
    sa.Column('notifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_classifier_entries_group'), 'classifier_entries', ['group'], unique=False)
    op.create_table('evaluations',
    sa.Column('attempt_id', sa.String(length=16), nullable=False),
    sa.Column('assessor_version', sa.String(length=32), nullable=False),
    sa.Column('time_score', sa.Integer(), nullable=False),
    sa.Column('correctness_score', sa.Integer(), nullable=False),
    sa.Column('grammar_score', sa.Integer(), nullable=False),
    sa.Column('semantic_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('grammar_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_comment', sa.String(length=4000), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generated_at', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('group_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.String(length=32), nullable=False),
    sa.Column('report_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('group_insights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('charts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('static', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_reports_session_id'), 'group_reports', ['session_id'], unique=True)
    op.create_table('incident_cards',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('ticket_no', sa.Integer(), nullable=False),
    sa.Column('situation_no', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('address', sa.String(length=600), nullable=False),
    sa.Column('address_refined', sa.String(length=600), nullable=True),
    sa.Column('caller', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('victims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('no_ambulance', sa.Boolean(), nullable=True),
    sa.Column('cross_region', sa.Boolean(), nullable=True),
    sa.Column('expected_services', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('duplicate_of', sa.String(length=16), nullable=True),
    sa.Column('created_by_student_id', sa.String(length=16), nullable=True),
    sa.Column('mode_origin', sa.String(length=16), nullable=False),
    sa.Column('source_attempt_id', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_cards_group'), 'incident_cards', ['group'], unique=False)
    op.create_table('kb_articles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_articles_group'), 'kb_articles', ['group'], unique=True)
    op.create_table('profile_mapping',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=160), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('incident_groups', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('service_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('report_feedback',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=False),
    sa.Column('teacher_id', sa.String(length=16), nullable=False),
    sa.Column('teacher_name', sa.String(length=160), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_feedback_session_id'), 'report_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_report_feedback_student_id'), 'report_feedback', ['student_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.String(length=32), nullable=False),
    sa.Column('export_formats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('student', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('time_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('grammar_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('charts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_comment', sa.String(length=4000), nullable=True),
    sa.Column('static', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_reports_student_id'), 'reports', ['student_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('card_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('validation_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_source'), 'scenarios', ['source'], unique=False)
    op.create_index(op.f('ix_scenarios_validation_status'), 'scenarios', ['validation_status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('teacher_id', sa.String(length=16), nullable=False),
    sa.Column('student_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scenario_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('card_source', sa.String(length=16), nullable=False),
    sa.Column('card_flow', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('finished_at', sa.String(length=32), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('paused_at', sa.String(length=32), nullable=True),
    sa.Column('parked', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('training_mode', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('exam', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_state'), 'sessions', ['state'], unique=False)
    op.create_index(op.f('ix_sessions_teacher_id'), 'sessions', ['teacher_id'], unique=False)
    op.create_table('streets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('okrug', sa.String(length=16), nullable=True),
    sa.Column('raion', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streets_name_norm'), 'streets', ['name_norm'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_at'), 'system_logs', ['at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_table('system_services',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('uptime_sec', sa.Integer(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_static',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('teacher_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.String(length=16), nullable=False),
    sa.Column('teacher_id', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_overrides_attempt_id'), 'teacher_overrides', ['attempt_id'], unique=False)
    op.create_table('ticket_audio',
    sa.Column('card_id', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=True),
    sa.Column('transcript', sa.String(length=4000), nullable=False),
    sa.Column('voice', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=600), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_ticket_audio_status'), 'ticket_audio', ['status'], unique=False)
    op.create_table('training_materials',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=16), nullable=False),
    sa.Column('uploaded_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('arm_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=160), nullable=True),
    sa.Column('assigned_groups', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('reason', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_table('student_ratings',
    sa.Column('student_id', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weak_groups', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'mode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_ratings')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('training_materials')
    op.drop_index(op.f('ix_ticket_audio_status'), table_name='ticket_audio')
    op.drop_table('ticket_audio')
    op.drop_index(op.f('ix_teacher_overrides_attempt_id'), table_name='teacher_overrides')
    op.drop_table('teacher_overrides')
    op.drop_table('system_static')
    op.drop_table('system_settings')
    op.drop_table('system_services')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_streets_name_norm'), table_name='streets')
    op.drop_table('streets')
    op.drop_index(op.f('ix_sessions_teacher_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_state'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scenarios_validation_status'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_source'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_reports_student_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_report_feedback_student_id'), table_name='report_feedback')
    op.drop_index(op.f('ix_report_feedback_session_id'), table_name='report_feedback')
    op.drop_table('report_feedback')
    op.drop_table('reference')
    op.drop_table('profile_mapping')
    op.drop_index(op.f('ix_kb_articles_group'), table_name='kb_articles')
    op.drop_table('kb_articles')
    op.drop_index(op.f('ix_incident_cards_group'), table_name='incident_cards')
    op.drop_table('incident_cards')
    op.drop_index(op.f('ix_group_reports_session_id'), table_name='group_reports')
    op.drop_table('group_reports')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_classifier_entries_group'), table_name='classifier_entries')
    op.drop_table('classifier_entries')
    op.drop_index(op.f('ix_card_work_messages_attempt_id'), table_name='card_work_messages')
    op.drop_index(op.f('ix_card_work_messages_at'), table_name='card_work_messages')
    op.drop_table('card_work_messages')
    op.drop_table('card_runtime')
    op.drop_index(op.f('ix_calibration_samples_attempt_id'), table_name='calibration_samples')
    op.drop_table('calibration_samples')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_attempts_student_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_session_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_card_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_assignments_teacher_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_state'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_assignment_attempts_student_id'), table_name='assignment_attempts')
    op.drop_index(op.f('ix_assignment_attempts_attempt_id'), table_name='assignment_attempts')
    op.drop_index(op.f('ix_assignment_attempts_assignment_id'), table_name='assignment_attempts')
    op.drop_table('assignment_attempts')
    op.drop_index(op.f('ix_arm_card_fixtures_number'), table_name='arm_card_fixtures')
    op.drop_table('arm_card_fixtures')
    op.drop_table('addresses')
    # ### end Alembic commands ###
