export { DEFAULT_ANSWER_SEC, DEFAULT_SUBMIT_SEC, resolveNorms, resolveTimeLimitSec } from "./model/norms";
export type { AttemptNorms } from "./model/norms";
export { answerWait, examRemainingSec, formatClock, processingWait, talkSeconds } from "./model/timers";
export type { NormState } from "./model/timers";
export { attemptPhase, canAnswer, canEdit, canSubmit, hasAnswerTimeout } from "./model/phase";
export { isEmergencyAudio, isReplayBlocked } from "./model/phase";
export type { AttemptPhase } from "./model/phase";
export { isHintDue, pickHintStep } from "./model/hints";
export type { HintProgress } from "./model/hints";
export { createTicker, TICK_MS } from "./lib/ticker";
export { useNow } from "./model/useNow";
