/*
 * Пути эндпоинтов мок-слоя относительно baseUrl (spec/03-architecture.md → «Мок-слой API»).
 * Корневые route handlers: app/api/mock/<путь>/route.ts. Id кодируются encodeURIComponent.
 */
const segment = (id: string) => encodeURIComponent(id);

export const API_PATHS = {
  login: "/auth/login",
  authPolicy: "/auth/policy",
  reference: "/reference",
  classifier: "/classifier",
  cards: "/cards",
  card: (cardId: string) => `/cards/${segment(cardId)}`,
  cardStatus: (cardId: string) => `/cards/${segment(cardId)}/status`,
  cardLinks: (cardId: string) => `/cards/${segment(cardId)}/links`,
  cardWorkLines: (cardId: string) => `/cards/${segment(cardId)}/worklines`,
  cardReminders: (cardId: string) => `/cards/${segment(cardId)}/reminders`,
  cardSms: (cardId: string) => `/cards/${segment(cardId)}/sms`,
  cardRecordings: (cardId: string) => `/cards/${segment(cardId)}/recordings`,
  cardCalls: (cardId: string) => `/cards/${segment(cardId)}/calls`,
  cardAttempt: (cardId: string) => `/cards/${segment(cardId)}/attempt`,
  attemptProgress: (attemptId: string) => `/attempts/${segment(attemptId)}/progress`,
  callReply: "/calls/reply",
  scenarios: "/scenarios",
  scenario: (scenarioId: string) => `/scenarios/${segment(scenarioId)}`,
  scenarioValidate: (scenarioId: string) => `/scenarios/${segment(scenarioId)}/validate`,
  scenarioGenerate: "/scenarios/generate",
  trainingCards: "/training-cards",
  materials: "/materials",
  profileMapping: "/profile-mapping",
  grammarCheck: "/grammar-check",
  sessions: "/sessions",
  sessionStart: (sessionId: string) => `/sessions/${segment(sessionId)}/start`,
  sessionStop: (sessionId: string) => `/sessions/${segment(sessionId)}/stop`,
  sessionFeed: (sessionId: string) => `/sessions/${segment(sessionId)}/feed`,
  sessionControl: (sessionId: string) => `/sessions/${segment(sessionId)}/control`,
  users: "/users",
  reports: "/reports",
  reportJournal: "/reports/journal",
  reportFeedback: "/reports/feedback",
  attemptEvaluation: (attemptId: string) => `/attempts/${segment(attemptId)}/evaluation`,
  adminUsers: "/admin/users",
  adminUser: (userId: string) => `/admin/users/${segment(userId)}`,
  adminUserBlock: (userId: string) => `/admin/users/${segment(userId)}/block`,
  adminUserUnblock: (userId: string) => `/admin/users/${segment(userId)}/unblock`,
  adminUserResetPassword: (userId: string) => `/admin/users/${segment(userId)}/reset-password`,
  adminUserToggleActive: (userId: string) => `/admin/users/${segment(userId)}/toggle-active`,
  adminServices: "/admin/services",
  adminAudit: "/admin/audit",
  adminSettings: "/admin/settings",
  /* Раздел «Система» администратора (фаза 4.2). */
  systemServices: "/admin/system/services",
  systemServiceAction: (serviceId: string) => `/admin/system/services/${segment(serviceId)}/action`,
  systemSettings: "/admin/system/settings",
  systemLogs: "/admin/system/logs",
  systemMonitoring: "/admin/system/monitoring",
  systemUsageStats: "/admin/system/usage-stats",
} as const;
