/*
 * Public API сегмента shared/api: контрактные типы, клиент мок-слоя /api/mock/* и статика волны 0.
 * Серверная часть мок-слоя (ридеры, store, хелперы handlers) — только "@/shared/api/mock" из app/api/**.
 * Имена прототипа волны 0 (ArmCardFixture, CardEvent, NotificationEntry, NotificationStatus, Report,
 * Session, StatusRef, WorkLine) пока выведены из JSON; их контрактные версии — с суффиксом Contract.
 */
export { armCardFixtures, cards, classifier, groupReport, reference, reports, scenarios } from "./mocks";
export { sessions, users } from "./mocks";
export { ApiError, apiClient, buildQuery, createApiClient } from "./client";
export type { ApiClient, ApiClientConfig, ApiRequestOptions } from "./client";
// ИИ-модуль: заменить на реальный сервис — вызывающий код зависит от AiGateway, MockAiGateway подменяется инъекцией.
export type { AiGateway, AiProvider, AiResponse } from "./ai-gateway";
export { createMockAiGateway, MockAiGateway } from "./ai-gateway.mock";
export type { MockAiGatewayDeps } from "./ai-gateway.mock";
export { API_PATHS, adminGetSettings, adminListAudit, adminListServices, adminListUsers } from "./endpoints";
export { adminToggleUserActive, createScenario, createSession, getAttemptEvaluation } from "./endpoints";
export { adminSystemApi, getAuditLog, getSystemLogs, getSystemMonitoring } from "./endpoints";
export { getSystemServices, getSystemSettings, getSystemUsageStats } from "./endpoints";
export { patchSystemSettings, postSystemServiceAction } from "./endpoints";
export type { AdminSystemApi } from "./endpoints";
export { getCard, getCardRecordings, getCardSms, getCards, getClassifier, getReference } from "./endpoints";
export { getReports, getSessionFeed, listScenarios, listSessions, login, postCardLinks } from "./endpoints";
export { postCardReminder, postCardSms, postCardStatus, postCardWorkline, startSession } from "./endpoints";
export { getStudentReports, stopSession, validateScenario } from "./endpoints";
export { getSessionControl, listUsers, postSessionControl } from "./endpoints";
export { getReportJournal, postAttemptEvaluation, postReportFeedback } from "./endpoints";
export { postCallReply, postCardCall } from "./endpoints";
export { postAttemptProgress, postCardAttempt } from "./endpoints";
export { LOGIN_FAILURE_MESSAGES, getAuthPolicy, mapLoginError } from "./endpoints";
export { checkGrammar, deleteScenario, generateScenarios, getProfileMapping } from "./endpoints";
export { getScenario, listMaterials, listTrainingCards, saveProfileMapping } from "./endpoints";
export { updateScenario, uploadMaterial } from "./endpoints";
export { ADMIN_USER_FAILURE_MESSAGES, adminCreateUser, adminResetUserPassword } from "./endpoints";
export { adminSetUserActive, adminSetUserRole, adminUpdateUser, mapAdminUserError } from "./endpoints";
export type { AdminUserFailure, AdminUserFailureReason } from "./endpoints";
export type { LoginFailure, LoginFailureReason } from "./endpoints";
export type { ArmCardFixture, CardEvent, NotificationEntry, NotificationStatus } from "./prototype-types";
export type { Report, Session, StatusRef, WorkLine } from "./prototype-types";
export type { ApiErrorBody, ApiErrorCode, ArmCardAddress, ArmCardApplicant } from "./types";
export type { ArmCardCasualties, ArmCardFixture as ArmCardFixtureContract, ArmCardId } from "./types";
export type { ArmCardPhones, ArmCardWhat, AuditLogEntry, AuthPolicy, AuthSession } from "./types";
export type { CallerStatus } from "./types";
export type { CardDetails, CardEvent as CardEventContract, CardFlowItem, CardId, CardLink } from "./types";
export type { CardLinkRole, CardLinksResponse, CardRecording, CardReminder } from "./types";
export type { CardReminderRequest, CardRuntimeState, CardSms, CardSmsRequest, CardSource } from "./types";
export type { CardStatus, CardStatusDef, CardStatusEvent, CardStatusMark, CardStatusRef } from "./types";
export type { CardStatusRequest, CardWorkLine, CardWorkLineRequest, CardsQuery, ChartData } from "./types";
export type { ChartKind, ClassifierEntry, ClassifierMeta, ClassifierNotification } from "./types";
export type { ClassifierQuery, ClassifierRowsRef, DdsStatus, DdsStatusDef, Difficulty } from "./types";
export type { District, ErrorSeverity, Etalon, Evaluation, EvaluationError, GeoPoint } from "./types";
export type { GrammarError, GrammarErrorType, GroupReport, GroupReportCharts, IncidentCaller } from "./types";
export type { IncidentCard, IncidentCardId, IncidentVictims, InternalNumber, LabeledSeries } from "./types";
export type { LoginRequest, NotificationAddedBy } from "./types";
export type { NotificationEntry as NotificationEntryContract, NotificationMode, PageQuery } from "./types";
export type { PageResponse, PhoneCall, PublicUser, QueryParams, QueryScalar, QueryValue } from "./types";
export type { ReferenceData, Report as ReportContract, ReportCharts, ReportError } from "./types";
export type { ReportExportFormat, ReportGrammarError, ReportStageAttempt, ReportStudent } from "./types";
export type { EvaluationOverrideRequest, ReportFeedback, ReportFeedbackRequest } from "./types";
export type { ReportJournalFilters, ReportJournalQuery, ReportJournalResponse } from "./types";
export type { ReportJournalRow, ReportJournalStatus, ReportJournalStudent } from "./types";
export type { ReportTimeMetric, ReportsResponse, Role, Scenario, ScenarioCreateRequest } from "./types";
export type { ScenarioHints, ScenarioLevel, ScenarioListQuery, ScenarioMode, ScenarioSource } from "./types";
export type { ScenarioTimeNorms, ScenarioValidateAction, ScenarioValidateRequest } from "./types";
export type { ScenarioValidation, ScenarioValidationStatus, ServiceKind, ServiceNotification } from "./types";
export type { GrammarCheckRequest, MaterialFormat, MaterialUploadRequest } from "./types";
export type { ProfileMappingRow, ProfileMappingSaveRequest, ScenarioGenerateRequest } from "./types";
export type { ScenarioUpdateRequest, TrainingMaterial } from "./types";
export type { ServiceRef, ServiceStatus, ServiceStatusDef, ServiceStatusEvent } from "./types";
export type { Session as SessionContract, SessionCreateRequest, SessionFeedEvent } from "./types";
export type { SessionFeedEventKind, SessionFeedQuery, SessionFeedResponse, SessionListQuery } from "./types";
export type { SessionControlAction, SessionControlRequest, SessionControlResponse } from "./types";
export type { SessionIssueOrder, SessionPlan, UserListQuery } from "./types";
export type { SessionState, SmsDirection, SuccessCriteria, SystemService, SystemServiceState } from "./types";
export type { SystemSettings, TeacherOverride, ToggleUserActiveRequest, TrainingCard } from "./types";
export type { AuditEventType, AuditLogQuery, SystemIntegrity, SystemLogEntry } from "./types";
export type { SystemLogLevel, SystemLogsQuery, SystemMonitoring, SystemServiceAction } from "./types";
export type { SystemServiceActionRequest, SystemServicesResponse, SystemSettingsPatch } from "./types";
export type { UsageStats, UsageStatsPeriod, UsageStatsPeriodId, UsageStatsQuery } from "./types";
export { SETTINGS_LIMITS, SETTINGS_MESSAGES, SETTINGS_NORMS } from "./validation/settings";
export { validateSettings, validateSettingsPatch } from "./validation/settings";
export type { SettingsFieldError } from "./validation/settings";
export type { TranscriptLine, TranscriptSpeaker, User, UserRole } from "./types";
export type { CardSearchFilters, WorkLine as WorkLineContract } from "./types";
export type { CallReply, CallReplyRequest, CallTurn, CallVoice, CardCallRequest } from "./types";
export type { CardCallResponse } from "./types";
export type { AttemptProgressRequest, CardAttemptRequest, CardAttemptResponse } from "./types";
export type { AdminUserActionRequest, AdminUserCreateRequest, AdminUserListQuery } from "./types";
export type { AdminUserPasswordResetResponse, AdminUserRoleFields, AdminUserState } from "./types";
export type { AdminUserUpdateRequest } from "./types";
